[[main]]
  name = "GitHub"
  url = "https://github.com/l10178"
  weight = 10

# [[social]]
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/in/henkverlinde/"
#   weight = 20

# [[social]]
#   name = "Twitter"
#   url = "https://twitter.com/henkverlinde"
#   weight = 30
